# Make libs
all: pins pwm setup timing threading
pins: pins.sld
	cyclone pins.sld
pwm: pwm.sld
	cyclone pwm.sld
setup: setup.sld
	cyclone setup.sld
timing: timing.sld
	cyclone timing.sld
threading: threading.sld
	cyclone threading.sld
misc: misc.sld
	cyclone misc.sld
